### ISSUE TITLE
Add an output with the number of total items found

### ISSUE THREAD

**Issue by oncletom** [actionsflow/actionsflow-action#1]
Currently, the output states if the build was successful or not.

But sometimes the build is successful, although no new items have been found (in the case of RSS polling for example).

In that case, having this kind of informations could be used as a condition to run the subsequent steps (setup `act`, etc.).

If there is no new item, I could totally skip the next steps and end the task even sooner.

**Comment by theowenyoung** [comment]
yeah, that makes sense.

But it may be difficult to get the result from actionsflow, cause sometimes this action exec actionsflow through shell, in that case, that may be difficult to get the result, stdout is chaos

Another way is to detect `dist/workflows` folder, if there are any `.yml` files, then we should do next step.

By the way, Is the next step taking so much time? I supposed that act step will take a couple of second

**Comment by oncletom** [comment]
Well, 0 seconds for both of the setup and run. So it might be a worthless effort.

thanks for your reply.
Love the tool :-)
